# created by Iran R. Roman <iran@ccrma.stanford.edu>
NUMPY_SEED: 1 # must be greater than 0
TRAIN:
  ENABLE: False
TEST:
  ENABLE: True
DESSEO:
  FS: 100
  ALPHA: 0.011  #-1.240 #0.00  #-1.34 #-2.137
  BETA1: -0.955 #0.800  #-1.27 #-1.13 #1.729
  BETA2: -0.935 #-0.923 #-1.41 #-0.57 #-1.231
  CS:    0.573  #0.120  #0.22 #0.48 #4.792
  CR:    0.271  #1.214  #0.79 #0.00 #0.043
  CW:    0.484  #1.392  #1.54 #0.88 #0.400
  F0:    3.441  #6.874  #7.04 #7.32 #0.479
  RND_INIT: 
    ENABLE: False
DATASET:
  NAME: 'Golumbic'
  PATH: 'Golumbic_speech_data'
  PERCENT_VAL: 20
  LOWPASS_CUTOFF: 10 # Hertz
  DIFF: True
  STANDARDIZE: True
DATA_LOADER:
  NUM_WORKERS: 12
OUT_PLOTS: 'plots'
