# created by Iran R. Roman <iran@ccrma.stanford.edu>
NUMPY_SEED: 1 # must be greater than 0
TRAIN:
  ENABLE: False
TEST:
  ENABLE: True
DESSEO:
  FS: 100
  ALPHA: -2.137
  BETA1: 1.729
  BETA2: -1.231
  F0: 4.792
  CS: 0.043
  CR: 0.400
  CW: 0.479
  RND_INIT: 
    ENABLE: False
DATASET:
  NAME: 'Golumbic'
  PATH: 'Golumbic_speech_data'
  PERCENT_VAL: 20
  LOWPASS_CUTOFF: 10 # Hertz
  DIFF: True
  STANDARDIZE: True
DATA_LOADER:
  NUM_WORKERS: 12
OUT_PLOTS: 'plots'
